### ISSUE TITLE
Formatter just runs once on initial install

### ISSUE THREAD

**Issue by PicassoCT** [Koihik/sublime-lua-format#12]
I installed the Package/Plugin LuaFormatter. It seemed to work fine at the time (as in i was able to run it on multiple files, via the shortcut).
After closing sublime and restarting my pc, however i ran into problems. Every time i try to auto-format my code, this message appears in the console.
```

Package Control: No updated packages
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/home/picasso/.config/sublime-text-3/Packages/LuaFormatter/LuaFormatter.py", line 21, in run
    process = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
```

**Comment by t1-10** [comment]
Fix: `chmod +x ~/Library/Application Support/Sublime Text 3/Packages/LuaFormatter/bin/darwin/lua-format`

**Comment by bofm** [comment]
Fix: `chmod +x ~/"Library/Application Support/Sublime Text 3/Packages/LuaFormatter/bin/darwin/lua-format"`
